# Generated by Django 3.0.1 on 2019-12-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='text',
            new_name='description',
        ),
    ]
