# Generated by Django 3.0.1 on 2019-12-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191220_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='text',
            new_name='description',
        ),
    ]
